baseURL = "https://example.com"

ContentLanguage = "nl"

# The perfect theme for Spar websites!
Theme = "Spar"

# About your website
Title = "Spar Pater"
Description = "Supermarkt uit Exloo"
Keywords = "Pater, Spar, Supermarkt, Boodschappen, winkel, Exloo, Borger-Odoorn, Drenthe, Hunebed highway, bezorgservice, maaltijdservice, Eet smakelijk!, de ambachtelijke bakker, Bakkerij Beukeveld, gebakservice, lunchservice, slijterij, belkaarten, beltegoed, internettegoed, bloemen, fruitmanden, barbeque, stomerijservice, PostNl,  post, pakketservice, cadeaukaarten, zelfzorg geneesmiddelen, OV-oplaadpunt"

# Who are you?
defaultAuthor = "Dennis Pater"

# Footer
Footer = ""

# Menu
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Service"
    pre = "pen-tool"
    url = "/service/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.homenav]]
    name = "Webwinkel"
    url = "http://exloo.spar.nl"
    weight = 1
